name: Publish temp site

on:
  push:
    branches:
      - '*doc/*'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-workflow-publish-doc:
    uses: ./.github/workflows/wc_publishSite.yml
    with:
      scope: "uploadDoc"
