name: Publish temp site
on:
  push:
    branches:
      - '*doc/*'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    if: github.repository != 'hablapps/doric'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Check, build and doc ðŸŽ¯
        uses: ./.github/actions/check_build_and_doc
        with:
          testing: false
      - name: Publish documentation ðŸ“‘
        uses: ./.github/actions/publish_doc
      - name: Cleaning for cache ðŸš¯
        uses: ./.github/actions/clean_cache
